# Generated by Django 4.2.9 on 2024-02-01 08:44

from django.db import migrations, models


def migrate_position_to_extras(apps, schema_editor):
    Fixture = apps.get_model('tournaments', 'Fixture')
    for fixture in Fixture.objects.using(schema_editor.connection.alias).all():
        fixture.extras = dict(position = fixture.position)
        fixture.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='extras',
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(migrate_position_to_extras),
        migrations.RemoveField(
            model_name='fixture',
            name='position',
        ),
    ]
