# Generated by Django 4.2.15 on 2025-03-14 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_participant_from_user(apps, schema_editor):
    Participation = apps.get_model('tournaments', 'Participation')
    Participant = apps.get_model('tournaments', 'Participant')
    for participation in Participation.objects.using(schema_editor.connection.alias).all():
        participant, created = Participant.objects.get_or_create(user=participation.user, defaults={'name': participation.user.username})
        participation.participant = participant
        participation.save()


def set_user_from_participant(apps, schema_editor):
    Participation = apps.get_model('tournaments', 'Participation')
    for participation in list(Participation.objects.using(schema_editor.connection.alias).all()):
        if participation.participant.user is not None:
            participation.user = participation.participant.user
            participation.save()
        else:
            participation.delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0002_remove_fixture_position_fixture_extras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('tournament', 'podium_position'), ('tournament', 'slot_id')},
        ),
        migrations.AddField(
            model_name='participation',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='tournaments.participant'),
        ),
        migrations.RunPython(
            set_participant_from_user,
            set_user_from_participant,
        ),
        migrations.AlterField(
            model_name='participation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='tournaments.participant'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixtures1', to='tournaments.participant'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixtures2', to='tournaments.participant'),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('tournament', 'participant'), ('tournament', 'podium_position'), ('tournament', 'slot_id')},
        ),
        migrations.RemoveField(
            model_name='participation',
            name='user',
        ),
    ]
