# Generated by Django 4.2.15 on 2025-03-13 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_alter_participant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixtures1', to='tournaments.participant'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixtures2', to='tournaments.participant'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation', to='tournaments.participant'),
        ),
    ]
