# Generated by Django 4.2.15 on 2025-03-13 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_fixture_player1_alter_fixture_player2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='tournaments.participant'),
        ),
    ]
