# Generated by Django 4.2.15 on 2025-03-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_alter_participation_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
