name: Post pull request comment

on:
  workflow_run:
    workflows: [Test suite]
    types: [completed]

jobs:
  post_pr_comment:
    uses: BMCV/github-workflows/.github/workflows/post-pr-comment.yml@main
