name: Post pull request comment

on:
  workflow_run:
    workflows: [Test suite]
    types: [completed]

permissions:
  pull-requests: write

jobs:
  post_pr_comment:
    uses: BMCV/github-workflows/.github/workflows/coverage-post-pr-comment.yml@main
    secrets:
      github-auth: ${{ secrets.GITHUB_TOKEN }}
