name: Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ['master']

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:

  run_tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - "3.9"
        - "3.10"

    steps:

    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
        
    - name: Run tests
      uses: kostrykin/report-test-coverage-action@v1.0.0
      with:
        report: ${{ strategy.job-index == 0 }}
        gist-id: bb85310a74d6b05330d230443007b878
        github-auth: ${{ secrets.GITHUB_TOKEN }}
        gist-auth: ${{ secrets.GIST_SECRET }}
        gist-filename: tournaments.json
        working-directory: tournaments
